spring.application.name=GloSportSpring

server.port=1111

spring.datasource.url=jdbc:postgresql://localhost:5432/glosport_db
spring.datasource.username=postgres
spring.datasource.password=Root@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

PlayerService.PLAYER_NOT_FOUND=Player details are not found in the database for the given player id: 
PlayerService.EMAIL_ALREADY_EXISTS=Email id is already registered in the database for another player: 

EquipmentService.EQUIPMENT_NOT_FOUND=Equipment details are not found in the database for the given equipment id: 